
#-----------------------
# General Configuration
#-----------------------

version: 5.2.{build}

# for now, only build master branches
branches:
  # whitelist
  only:
    - master


#---------------------------
# Environment Configuration
#---------------------------

image: Visual Studio 2015

environment:
  DEPSPKG: osrm-deps-win-x64-14.0.7z

init:
  - git config --global core.autocrlf input

# clone directory (on build host)
clone_folder: c:\projects\osrm

# fetch repo as zip archive
shallow_clone: true

matrix:
  fast_finish: true

install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall" amd64'
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin\amd64;%PATH%
  - set OSRMDEPSDIR=%PROJECT_DIR%/osrm-deps
  - set PREFIX=%OSRMDEPSDIR%/libs
  - set BOOST_ROOT=%OSRMDEPSDIR%/boost
  - set BOOST_LIBRARYDIR=%BOOST_ROOT%/lib
  - set TBB_INSTALL_DIR=%OSRMDEPSDIR%/tbb
  - set TBB_ARCH_PLATFORM=intel64/vc14


#---------------------
# Build Configuration
#---------------------

platform: x64

configuration:
  - Debug
  - Release
  
build:
  parallel: true
  project: OSRM.sln
  
  verbosity: normal

before_build:
  # setup dependencies
  - ps: Invoke-WebRequest https://mapbox.s3.amazonaws.com/windows-builds/windows-build-deps/$env:DEPSPKG -OutFile $env:PROJECT_DIR\$env:DEPSPKG
  - 7z -y x %DEPSPKG% | %windir%\system32\FIND "ing archive"
  # setup build directory for cmake
  
#after_build:


build_script:
  - mkdir build
  - cd build
  - cmake .. \
     -G "Visual Studio 14 2015 Win64" \
     -DBOOST_ROOT=%BOOST_ROOT% \
     -DBOOST_LIBRARYDIR=%BOOST_LIBRARYDIR% \
     -DBoost_ADDITIONAL_VERSIONS=1.58 \
     -DBoost_USE_MULTITHREADED=ON \
     -DBoost_USE_STATIC_LIBS=ON \
     -DCMAKE_INSTALL_PREFIX=%PREFIX% \
     -DCMAKE_BUILD_TYPE=%CONFIGURATION%
  - cd ..

#environment:
#  matrix:
#  - configuration: Release
#  - configuration: Debug

# scripts that are called at very beginning, before repo cloning
#init:
#  - git config --global core.autocrlf input

#os: Visual Studio 2015

# clone directory
#clone_folder: c:\projects\osrm

#platform: x64

#build_script:
#  - CALL appveyor-build.bat

#test: off

#artifacts:
#  - path: osrm_Release.zip
#    name: osrm_Release.zip
#  - path: osrm_Debug.zip
#    name: osrm_Debug.zip

#branches:
#  only:
#    - master

#deploy:
#  provider: FTP
#  server:
#    secure: ef7oiQTTXFGt8NdNiOHm/uRFVrUttzyFbIlnaeHhQvw=
#  username:
#    secure: Bw+Se2GTJxA6+GtRkEc//tQSBHOuFIuJHBjFwR9cD+8=
#  password:
#    secure: eqwESZqxMXC/j5mOCpaXuw==
#  folder: /
#  enable_ssl: true
# active_mode: false
